### ISSUE TITLE
Typeable Reflection

### ISSUE THREAD

**Issue by crockeea** [ekmett/reflection#14]
It would be extremely useful to be able to get a `typeRep` for reflected types. Specifically, I'm hoping that `(Reifies s a, Typeable a) => Typeable s`, where `show $ typeRep (Proxy :: Proxy s)` outputs a unique ID, perhaps using TemplateHaskell support for global names, or something else like `Data.Unique.ID`.

I don't know much about the magic going on in `reify`, but is something like this doable?

**Comment by ekmett** [comment]
A form of typeable reflection is implemented inside of `lens` these days. It was needed to make `Control.Exception.Lens` work after changes were made to `Typeable`.

http://hackage.haskell.org/package/lens-4.11.1/docs/Control-Lens-Internal-Reflection.html

We could think about moving it back home to here.

**Comment by treeowl** [comment]
It's been moved, so this issue can, technically, be closed. However, the code has no comments in it and is far from obvious. The `Typeable a` constraint seems very strange from the outside; everything else seems strange from the inside.

**Comment by ekmett** [comment]
The implementation does what it needs to do to let me fabricate `Exception` instances in a `post-AutoDeriveTypeable` world.  I could definitely stand to document it better, but it is basically the old slow path with a slight tweak.
