### ISSUE TITLE
Absorb or take over reflection-extras

### ISSUE THREAD

**Issue by rpglover64** [ekmett/reflection#22]
[reflection-extras](http://hackage.haskell.org/package/reflection-extras) ([git repository](http://github.com/jfischoff/reflection-extras)) depends on old versions of `base` and `lens` and hasn't been updated in 2 years. It would be nice if it continued to work, given how enticing the `using (Monoid (+) 0) $ mempty <> 10 <> 12 -- ==> 22` example is.

**Comment by ekmett** [comment]
I'd rather not absorb that material into this package. It is a nice example, but the details of every time you want to do something like that vary so much that it is a very ugly solution. Perhaps @jfischoff can be enticed into maintaining it more actively.

**Comment by jfischoff** [comment]
I rather give it away. Don't have the time now and it was more than anything a chance to play around with reflection.

**Comment by ekmett** [comment]
Fair enough. If you add me to the maintainer group on hackage for it then I might move Given out into that package and use this as an excuse to breathe some life into it.

**Comment by jfischoff** [comment]
Done :)
