### ISSUE TITLE
can't reify Nat kinds

### ISSUE THREAD

**Issue by ghorn** [ekmett/reflection#23]
Is this a fundamental limitation?

**Comment by ekmett** [comment]
Not exactly. The same trick I use to generate a dictionary for `Reifies` could be applied to `KnownNat`. We could add a `reifyNat` combinator that explicitly reifies just to just get a `KnownNat` dictionary.

**Comment by ghorn** [comment]
What about PolyKinds?

**Comment by ekmett** [comment]
It isn't that simple. If we let it float into _all_ kinds then we get a problem. You're effectively allowing folks to create in nested scope a member of every kind. e.g. for kind () then you'd have multiple distinguishable types inhabiting the kind: '(), and each thing you just reified, which is kind of a mess. Adding a one-off combinator for reifying a KnownNat or a KnownSymbol seems the lesser of evils.

**Comment by ekmett** [comment]
(Also the Magic trick doesn't work in a general polykinded setting for various technical reasons.)

**Comment by ekmett** [comment]
HEAD now has `reifyNat` that works on 7.10+

**Comment by ghorn** [comment]
ty

**Comment by ekmett** [comment]
I just managed to get it to work on 7.8+ actually.

**Comment by echatav** [comment]
Thanks!
