### ISSUE TITLE
Semigroup-Monoid-Proposal

### ISSUE THREAD

**Issue by ggreif** [ekmett/reflection#39]
needed for GHC 8.4 is not implemented. Causes compile errors with GHC HEAD.

**Comment by claudeha** [comment]
Indeed, with `ghc-8.4.1-alpha1` I get:

    Building library for reflection-2.1.2..
    [1 of 1] Compiling Data.Reflection  ( fast/Data/Reflection.hs, dist/dist-sandbox-a57ddd46/build/Data/Reflection.o )
    
    fast/Data/Reflection.hs:556:10: error:
        • Could not deduce (Semigroup (ReflectedMonoid a s))
            arising from the superclasses of an instance declaration
          from the context: Reifies s (ReifiedMonoid a)
            bound by the instance declaration
            at fast/Data/Reflection.hs:556:10-68
        • In the instance declaration for ‘Monoid (ReflectedMonoid a s)’
        |
    556 | instance Reifies s (ReifiedMonoid a) => Monoid (ReflectedMonoid a s) where
        |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by RyanGlScott** [comment]
Fixed in [`reflection-2.1.3`](http://hackage.haskell.org/package/reflection-2.1.3).
