### ISSUE TITLE
with ghc-9.10: Couldn't match expected type ‘ArgPat’ with actual type ‘Pat’

### ISSUE THREAD

**Issue by jwaldmann** [ekmett/reflection#56]
```
fast/Data/Reflection.hs:419:15: error: [GHC-83865]
    • Couldn't match expected type ‘ArgPat’ with actual type ‘Pat’
    • In the expression: SigP WildP na
      In the first argument of ‘LamE’, namely ‘[SigP WildP na]’
      In the first argument of ‘AppE’, namely ‘LamE [SigP WildP na] body’
    |
419 |         LamE [SigP WildP na] body `AppE` a
    |               ^^^^^^^^^^^^^
```

see https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/template-haskell/changelog.md?ref_type=heads#anchor-22200 ("Added new data type ArgPat with two constructors")

**Comment by RyanGlScott** [comment]
I'm aware of this, but I'd like to hold off until the discussion in https://gitlab.haskell.org/ghc/ghc/-/issues/24557 reaches a consensus.

**Comment by erikd** [comment]
#metoo .

**Comment by andreasabel** [comment]
This issue might resolve itself with the next alpha of GHC 9.10.

**Comment by erikd** [comment]
@andreasabel You mean `ghc-9.10.0.20240328` (which is `9.10.0-alpha2`)? I can confirm that it does not.

**Comment by RyanGlScott** [comment]
GHC 9.10.1-alpha3 is out, and I've confirmed that `reflection` builds without issue using that alpha. As such, I'll close this. Please re-open if there is something else I've missed.
